### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by kemeris2000** [Alef-Burzmali/netbox-data-flows#10]
Netbox version: 3.4.3

I get error when executing upgrade.sh. What could be a problem?

Collecting netbox_data_flows@ https://github.com/Alef-Burzmali/netbox-data-flows/releases/download/v0.4.0/netbox-data-flows-0.4.0.tar.gz
  Using cached netbox_data_flows-0.4.0-py3-none-any.whl
Collecting netbox-secretstore
  Using cached netbox_secretstore-1.4.1-py3-none-any.whl (66 kB)
Collecting netbox_attachments
  Using cached netbox_attachments-1.1.2-py3-none-any.whl (17 kB)
Collecting importlib
  Using cached importlib-1.0.4-py3-none-any.whl
Collecting pycryptodome
  Using cached pycryptodome-3.17-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Installing collected packages: netbox_data_flows, importlib, pycryptodome, netbox_attachments, netbox-secretstore
Successfully installed importlib-1.0.4 netbox-secretstore-1.4.1 netbox_attachments-1.1.2 netbox_data_flows-0.4.0 pycryptodome-3.17
Applying database migrations (python3 netbox/manage.py migrate)...
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "netbox_data_flows_dataflowgroup" does not exist
LINE 1: ... "netbox_data_flows_dataflowgroup"."tree_id" FROM "netbox_da...

**Comment by Alef-Burzmali** [comment]
Please use the latest version v0.4.1, it is already fixed.

Thanks

**Comment by kemeris2000** [comment]
Working fine with v0.4.2.

Than you [Alef-Burzmali](https://github.com/Alef-Burzmali)
