### ISSUE TITLE
import of data-flows is broken

### ISSUE THREAD

**Issue by anubisg1** [Alef-Burzmali/netbox-data-flows#14]
given the following:

![image](https://user-images.githubusercontent.com/4518931/221883161-f54222e2-4f98-4ae4-8844-1d2e2a66edaf.png)

the problems i see are:

1) protocols don't map correctly as seen here (it takes the values from status):

![image](https://user-images.githubusercontent.com/4518931/221883315-6a8b6e34-713a-40cd-b28a-31413a802fea.png)

2) no matter what i put there, nothing works (i tried with ICMP, icmp, TCP, tcp, enabled) 

 Record 1 protocol: Select a valid choice. icmp is not one of the available choices. 

3) it's not possible to import source/destination

**Comment by Alef-Burzmali** [comment]
Thanks for the report. Fixed in the new release.
