### ISSUE TITLE
Child Group Flow Count incorrect

### ISSUE THREAD

**Issue by zeddD1abl0** [Alef-Burzmali/netbox-data-flows#18]
Hi,

I love the concept of this plugin. Really useful.

I notice that, after adding a sub-group to a group, the number of flows on the child group is incorrect when you are looking from the parent:

![image](https://github.com/Alef-Burzmali/netbox-data-flows/assets/8335605/c087414d-02ea-4ad5-8edc-0c6cd338358e)

Everything shows up perfectly, but there should be a Count of 2 in the "Data Flows" column under the "Child Groups" heading.

**Comment by zeddD1abl0** [comment]
Just as an extra thing, it's probably redundant to have "Direct Members" and "Direct and Recursive Members" at the bottom. That might be better split into "Direct Members" and "Recursive Members"

**Comment by Alef-Burzmali** [comment]
Thanks for your feedback! The bug has been fixed (along with a few other counters that were incorrect in other tables) and I have removed the "direct members" from the second tables.
