### ISSUE TITLE
Separate "Source" and "Destination" on affected devices

### ISSUE THREAD

**Issue by zeddD1abl0** [Alef-Burzmali/netbox-data-flows#19]
Hi,

As a feature request, would it be possible to separate the "Source" data flows from the "Destination" data flows on the endpoint? For instance, if I have a device that initiates a few connections, and receives a few connections, it would make it much more visually obvious if the data flows that are "incoming" to this "Destination" are separated from those "outgoing" from this "Source".

Basically just having two headings on the "Data Flows" tab on an IP/VLAN/Prefix.

**Comment by Alef-Burzmali** [comment]
Hello
Thanks for the suggestion. I've changed the tab completely: now, it lists the object aliases, then the outgoing (source) data flows and the incoming (destination) data flows. I have remove the object alias tab that is now redundant. The data flow tab will show up if there is at least one alias for this object.
