### ISSUE TITLE
Add support to move NetBox Data Flows to plugins submenu

### ISSUE THREAD

**Issue by mjf** [Alef-Burzmali/netbox-data-flows#27]
With default to `False` let user to reincarnate the current menu placement with:

```python
PLUGINS_CONFIG = {
    'netbox_data_flows': {
        'top_level_menu': True,
    },
}
```

Plugin supporting this is for example `netbox-acls` (for inspiration).

**Comment by Alef-Burzmali** [comment]
Thanks for your suggestion. I'll add that option, but default to True as that seems to me more in line with the direction of NetBox's design to have many specialized sections.
