### ISSUE TITLE
Error on displaying group tree in application view

### ISSUE THREAD

**Issue by lajaunie** [Alef-Burzmali/netbox-data-flows#39]
hello,
i am testing your plugin and i note an error on displaying hierarchy of data flow groups.

First, i create an application named "Application".
I create a group named "Application"
I create a group named "From Application" with "Application" for parent
I create a group named "To Application" with "Application" for parent
I create a group named "Application Action"  with "From Application" for parent
All groups belong to application "Application"

And this is the result:
![image](https://github.com/user-attachments/assets/fc062a8d-182a-44b7-8ef2-43fcb385492d)

thank you

**Comment by Alef-Burzmali** [comment]
Thanks for the report. I'll need to check why it's ordered that way.
I will try to fix that for next release.
