### ISSUE TITLE
Port range are not saved with hyphen character

### ISSUE THREAD

**Issue by ugoleleux** [Alef-Burzmali/netbox-data-flows#43]
Hello,

I am facing a strange behaviour,
When I choose to register a source or a destination range of port using hyphen caracter
![image](https://github.com/user-attachments/assets/2cab18c1-9f14-4f3d-a922-3e8294199132)
it is well saved with the same format
![image](https://github.com/user-attachments/assets/6cbb75d7-f868-46a9-9a3a-713cff3827b0)
but when I go to edit it once again, the hyphen as been replaced by each ports in the range coma separated
![image](https://github.com/user-attachments/assets/78e44ce2-6e39-41c4-b826-ad7c32c2ebcb)
I can save and the UI is still showing a range of ports, but I think it will be difficult to handle when I will enter a range of thousand of ports.

I am also confused with the export format which is natively a square bracket list 
![image](https://github.com/user-attachments/assets/21c3331b-b9bf-407a-9e1d-a2aaef622176)
This format is not the same as any other netbox fields therefore I can't import it without removing the brackets in the first time

Thank you for reading my issue which is more a improvement suggestion.

Regards
Ugo

**Comment by Alef-Burzmali** [comment]
Hi. Thanks for the report, I've had a lot of trouble making that field work, but now I see that NetBox's Service forms behave better. I will see what I can do for the next release.

**Comment by Alef-Burzmali** [comment]
NetBox's services have exactly the same issue, but they are usually used with far fewer ports. I've overridden upstream's NumericArrayField to display the ranges in edit forms.

What tool are you using for your export? This is neither the native export to CSV nor what the API returns (an array of int, not a string), so I can't help you there.

**Comment by ugoleleux** [comment]
> NetBox's services have exactly the same issue, but they are usually used with far fewer ports. I've overridden upstream's NumericArrayField to display the ranges in edit forms.
> 
> What tool are you using for your export? This is neither the native export to CSV nor what the API returns (an array of int, not a string), so I can't help you there.

Hi,
thank you for your replies.
For the export, I use a custom export template in jinja2
```
[{% for object in queryset %}
{
  "id":"{{object.id}}",
  "name":"{{object.name}}",
  "status":"{{object.status}}",
  "protocol":"{{object.protocol}}",
  "application":"{{object.application}}",
  "source_ports":"{{object.source_ports}}",
  "destination_ports":"{{object.destination_ports}}",
  "sources":"{% for source in object.sources.all() %}{{ source.name }}{{ "," if not loop.last }}{% endfor %}",
  "destinations":"{% for destination in object.destinations.all() %}{{ destination.name }}{{ "," if not loop.last }}{% endfor %}",
  "description":"{{object.description}}",
  "comments":"{{object.comments}}",
  "tags":"{% for tag in object.tags.all() %}{{ tag.slug }}{{ "," if not loop.last }}{% endfor %}"
},
{% endfor %}]
```

**Comment by Alef-Burzmali** [comment]
Hi,
Ah, I see. Then, two easy options for the moment:
* You can export the list as a list of int, which will be valid JSON and correspond exactly to what is stored in the DB
```
  "source_ports": {{object.source_ports}},
  "destination_ports": {{object.destination_ports}},
```
* You can use these functions to get nicely formatted strings, with two caveats: an empty list is displayed as `"Any"`, which must be replaced by `""` before being reimported; and it's not supposed to be public API so it can be removed/renamed/changed in future updates.
```
  "source_ports": "{{object.source_port_list}}",
  "destination_ports": "{{object.destination_port_list}}",
```
* Or you can loop on them as you did for the sources, and use whatever formatting you prefer.

If you want a better support for that use case, please make a separate issue.

**Comment by ugoleleux** [comment]
Thank you very much for the hint.
I followed you advice and I removed the `""` in the jinja template :
```
  "source_ports": {{object.source_ports}},
  "destination_ports": {{object.destination_ports}},
```
And i can reimport data without any problem now.

Thanks again for your help.

Regards
Ugo
