### ISSUE TITLE
enhance edit data flows ports list

### ISSUE THREAD

**Issue by lvenier** [Alef-Burzmali/netbox-data-flows#48]
| Netbox Version |
| --- |
| 3.X & 4.X |

# Actual Behavior

When I create a data flow I have selected source ports from 1 to 65000 : 

![image](https://github.com/user-attachments/assets/bf8a3d0c-c128-4364-8e2a-cd6d70a0256e)

It looks good on the summary page.
When I want to edit the ports I get the following : 

![image](https://github.com/user-attachments/assets/42161262-5097-4945-ae63-e1855a79c423)

# Desired Behavior

As you can see the source ports is listing all the ports. From a UX perspective I believe it would be better to have : 

![image](https://github.com/user-attachments/assets/46f19e31-23db-45d0-8d64-fb76c281c77a)

Thanks

**Comment by Alef-Burzmali** [comment]
Hello LaV,

This should be already fixed in v1.0.6 (#43 ) that was released on Sunday.
