### ISSUE TITLE
allow the creation of flows having both TCP and UDP ports

### ISSUE THREAD

**Issue by anubisg1** [Alef-Burzmali/netbox-data-flows#8]
when creating a flow, only one protocol can be added.
In reality, especially when configuring firewall rules, we generally have tcp/port-number udp/por-number in the same rule/flow.

take for example DNS, that is both tcp and udp port 53 and should be marked as a single flow.

**Comment by Alef-Burzmali** [comment]
Thanks for the suggestion. This will be added in the next release

**Comment by anubisg1** [comment]
i have seen how this has been implemented and i have a question on the implementation or maybe on the expected way to model a flow.

when i create a firewall rule entry i can have multiple ports/protocls in a single rule.
for example, a typical rule used to handle mgmt traffic would be as follow:

rule name: Device Management out
- source: managed devices
- destination: monitoring server
- protocol/port:  syslog ( tcp/514 + udp/514 ) , ntp ( tcp/123 + udp/123 ), snmp-trap ( udp/162 ), tacacs ( tcp/49 ), icmp-echo, icmp-reply

rule name: Device Management in
- source: monitoring server
- destination: mananged devices
- protocol/ports: ssh ( tcp/22 ), snmp ( udp/161 ),  icmp-echo, icmp-reply


how would i model this?
the request was about allow to add in the same flow both tcp and udp ports, which does covers as a special case the "tcp+udp" that was just added.

**Comment by Alef-Burzmali** [comment]
I have created the discussion #11 to discuss that
